// `Env` is generated by `wrangler types` to match bindings in wrangler.jsonc.
export type AppBindings = Env & {
  AUTH0_AUDIENCE: string;
  AUTH0_ISSUER: string;
  SESSION_TOKEN_SECRET: string;
  
  AUTH0_DOMAIN: string;
  AUTH0_M2M_CLIENT_ID: string;
  AUTH0_M2M_CLIENT_SECRET: string;
  AUTH0_SPA_CLIENT_ID: string;
  AUTH0_CONNECTION: string;
  AUTH0_M2M_AUDIENCE: string;
  AUTH0_VIEWER_ROLE_ID: string;
};

export type AuthContext = {
  userId: string;
  permissions: ReadonlySet<string>;
};

export type AppVariables = {
  auth: AuthContext;
  requestId: string;
};
