// `Env` is generated by `wrangler types` to match bindings in wrangler.jsonc.
export type AppBindings = Env & {
  AUTH0_AUDIENCE: string;
  AUTH0_ISSUER: string;
};

export type AuthContext = {
  userId: string;
  permissions: ReadonlySet<string>;
};

export type AppVariables = {
  auth: AuthContext;
};
